version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment: 
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - user-data:/var/lib/postgresql/data/
    networks:
      - freaky

  backend:
    container_name: backend
    build: backend/
    ports:
      - "8080:8080"
    networks:
      - freaky
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING=postgresql://postgres:docker@db:5432/my_database
      # - DB_HOST=db
      # - DB_PORT=5432
      # - DB_USER=postgres
      # - DB_PASSWORD=docker
      # - DB_NAME=my_database
    volumes:
      - type: bind
        source: ./backend/app
        # source wants the dir to where we configured everything
        target: /app/app/
        # target wants the dir inside our instance (defn'd in our Dockerfile, where I renamed /backend/ to /app/)

  client:
    container_name: client
    build: client/
    ports:
      - "3000:3000"
    networks:
      - freaky
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ./client/src
        target: /app/src
      
networks:
  freaky:
    driver: bridge

volumes:
  user-data: 
